/** @type {import('./types').Certification[]} */
export const certifications = [
  {
    id: 'cs50',
    title: 'CS50: Introduction to Computer Science',
    issuer: 'Harvard',
    tag: 'harvard',
    category: 'Computer Science',
    date: '2024',
    url: '',
    color: '#B3453A',
  },
  {
    id: 'claude101',
    title: 'Claude 101',
    issuer: 'Anthropic',
    tag: 'anthropic',
    category: 'AI / ML',
    date: '2025',
    url: '',
    color: '#D97757',
  },
  {
    id: 'genai',
    title: 'Introduction to Generative AI',
    issuer: 'Google Cloud',
    tag: 'google',
    category: 'AI / ML',
    date: 'Jul 2026',
    url: '',
    color: '#5B8FD9',
  },
  {
    id: 'llm',
    title: 'Large Language Models',
    issuer: 'Google Cloud',
    tag: 'google',
    category: 'AI / ML',
    date: '2026',
    url: '',
    color: '#5B8FD9',
  },
  {
    id: 'pandas',
    title: 'Pandas',
    issuer: 'Kaggle',
    tag: 'kaggle',
    category: 'Data',
    date: '2024',
    url: '',
    color: '#4FA6A0',
  },
  {
    id: 'datacleaning',
    title: 'Data Cleaning',
    issuer: 'Kaggle',
    tag: 'kaggle',
    category: 'Data',
    date: '2024',
    url: '',
    color: '#4FA6A0',
  },
]
