/** @type {import('./types').CourseGroup[]} */
export const courses = [
  {
    id: 'harvard',
    issuer: 'Harvard',
    tag: 'harvard',
    category: 'Computer Science',
    date: '2024',
    courses: [
      { title: 'CS50: Introduction to Computer Science', category: 'Computer Science' },
    ],
    color: '#B3453A',
  },
  {
    id: 'mit',
    issuer: 'MIT',
    tag: 'mit',
    category: 'Computer Science',
    date: '2024-2025',
    courses: [
      { title: '6.034: Artificial Intelligence', category: 'Computer Science' },
      { title: '6.046J: Intro To Algorithms', category: 'Computer Science' },
      { title: '18.06: Linear Algebra (Gilbert Strang)', category: 'Mathematics' },
    ],
    color: '#A31F34',
  },
  {
    id: 'oxford',
    issuer: 'Oxford',
    tag: 'oxford',
    category: 'Artificial Intelligence',
    date: '2024',
    courses: [
      { title: 'An AI Stack', category: 'Artificial Intelligence' },
    ],
    color: '#002147',
  },
  {
    id: 'stanford',
    issuer: 'Stanford',
    tag: 'stanford',
    category: 'Artificial Intelligence',
    date: '2024-2025',
    courses: [
      { title: 'CS231n: Deep Learning for Computer Vision', category: 'Artificial Intelligence' },
      { title: 'CS224N: Natural Language Processing', category: 'Artificial Intelligence' },
    ],
    color: '#8C1515',
  },
  {
    id: 'uc-berkeley',
    issuer: 'UC Berkeley',
    tag: 'uc-berkeley',
    category: 'Data Science',
    date: '2024',
    courses: [
      { title: 'Data 100: Principles and Techniques of Data Science', category: 'Data Science' },
    ],
    color: '#003262',
  },
  {
    id: 'google',
    issuer: 'Google Cloud',
    tag: 'google',
    category: 'Artificial Intelligence',
    date: '2025-2026',
    courses: [
      { title: 'Introduction to Generative AI', category: 'Artificial Intelligence' },
      { title: 'Large Language Models', category: 'Artificial Intelligence' },
    ],
    color: '#5B8FD9',
  },
  {
    id: 'microsoft',
    issuer: 'Microsoft',
    tag: 'microsoft',
    category: 'Data Science',
    date: '2025-2026',
    courses: [
      { title: 'DP-900: Azure Data Fundamentals', category: 'Data Science' },
    ],
    color: '#737373',
  },
  {
    id: 'kaggle',
    issuer: 'Kaggle',
    tag: 'kaggle',
    category: 'Data Science',
    date: '2024-2025',
    courses: [
      { title: 'Pandas', category: 'Data Science' },
      { title: 'Data Cleaning', category: 'Data Science' },
    ],
    color: '#4FA6A0',
  },
  {
    id: 'anthropic',
    issuer: 'Anthropic',
    tag: 'anthropic',
    category: 'Artificial Intelligence',
    date: '2025',
    courses: [
      { title: 'Claude 101', category: 'Artificial Intelligence' },
      { title: 'AI Fluency', category: 'Artificial Intelligence' },
      { title: 'Claude Code 101', category: 'Artificial Intelligence' },
      { title: 'Claude Code in Action', category: 'Artificial Intelligence' },
      { title: 'Agent Skills', category: 'Artificial Intelligence' },
    ],
    color: '#D97757',
  },
  {
    id: 'campusx',
    issuer: 'CampusX',
    tag: 'campusx',
    category: 'Data Science',
    date: '2024-Cont.',
    courses: [
      { title: '100 Days of Machine Learning', category: 'Data Science' },
      { title: '100 Days of Deep Learning', category: 'Data Science' },
      { title: 'Natural Language Processing', category: 'Data Science' },
      { title: 'Generative AI', category: 'Artificial Intelligence' },

    ],
    color: '#0A0A23',
  },
  {
    id: 'freecodecamp',
    issuer: 'freeCodeCamp',
    tag: 'freecodecamp',
    category: 'Development',
    date: '2025',
    courses: [
      { title: 'Selenium & Browser Automation', category: 'Development' },
    ],
    color: '#0A0A23',
  },
]
