/** @import { WorkExperience } from './types' */

/** @type {WorkExperience[]} */
export const experience = [
  {
    id: 'exp-1',
    role: 'Co-Founder & Frontend Lead',
    company: 'QuickSite',
    location: 'Lahore, Punjab, Pakistan',
    duration: 'May 2025 - Present',
    description: 'Co-founded QuickSite to democratize professional web presence — building custom one-page websites for a fraction of the industry standard. Lead all frontend development, UI/UX design, and client-facing web architecture. Delivered 15+ production websites with 100% client satisfaction. Engineered responsive, performance-optimized sites averaging 95+ Lighthouse scores. Eliminated recurring hosting costs using free-tier platforms. Developed reusable component libraries reducing development time by 60%.',
    highlights: ['Built 15+ polished sites', 'Achieved 95+ Lighthouse scores', 'Cut hosting costs with free-tier setup'],
    technologies: ['React.js', 'Responsive Web Design', 'UI/UX Design', 'Performance Optimization', 'Vercel', 'Git/GitHub', 'Modern CSS', 'Web Development'],
    color: '#a78bfa',
    link: 'https://quick-site-00.vercel.app/',
  },
  {
    id: 'exp-2',
    role: 'Machine Learning Intern',
    company: 'FlyRank AI',
    location: 'Chicago, IL',
    duration: 'July 2026 - Present',
    description: 'Selected for FlyRank AI\'s competitive July 2026 internship cohort — a 12-week program focused on building production-level AI systems. Applied modern ML tooling with Python to develop models, evaluate scores, and generate actionable insights. Completed structured assignments and a capstone project delivering a portfolio-ready artifact. Worked asynchronously with mentors receiving iterative reviews. Earned verifiable credential, LinkedIn endorsement, and recommendation letter upon completion.',
    highlights: ['12-week AI internship cohort', 'Built production-style ML workflows', 'Delivered a portfolio-ready capstone'],
    technologies: ['Machine Learning', 'Python', 'AI Engineering', 'Model Evaluation', 'Production ML'],
    color: '#60a5fa',
    link: 'https://flyrank.ai/',
  },
  {
    id: 'exp-3',
    role: 'Data Analyst Intern',
    company: 'The GamiTron (PVT) LTD',
    location: 'Lahore',
    duration: 'June 2026 - August 2026',
    description: 'Contributed to the Analysis of real time company data, identifying trends and insights to support strategic decision-making. Utilized SQL and Python for data manipulation and visualization, ensuring accurate reporting and actionable intelligence.',
    highlights: ['Analyzed real-time company data', 'Identified trends and insights', 'Supported strategic decision-making'],
    technologies: ['Data Analysis', 'SQL', 'Python', 'Data Visualization'],
    color: '#34d399',
    link: 'https://www.thegamitron.com/',
  },
  {
    id: 'exp-4',
    role: 'Teaching Assistant — Programming Fundamentals',
    company: 'FAST NUCES, Lahore Campus',
    location: 'Lahore',
    duration: 'June 2026 - Present',
    description: 'Supported course delivery under Sir M. Naveed by managing quizzes, assignments, and the final project. Provided academic guidance, motivation, and leadership to help students strengthen their programming foundations and succeed in the course.',
    highlights: ['Guided programming labs', 'Managed quizzes and projects', 'Mentored students toward stronger fundamentals'],
    technologies: ['Programming Fundamentals', 'Academic Guidance', 'Course Management', 'Leadership'],
    color: '#f472b6',
    link: 'https://lhr.nu.edu.pk/',
  },
  {
    id: 'exp-5',
    role: 'Game Development Trainer',
    company: 'Government College University (GCU), Lahore',
    location: 'Lahore',
    duration: 'Oct 2022 - Nov 2023',
    description: 'Served as a Game Development Trainer at GCUL Freelancing and Skill Development Society (FSDS), teaching game development concepts and mentoring students in building interactive projects.',
    highlights: ['Taught game dev concepts', 'Mentored student projects', 'Delivered practical creative training'],
    technologies: ['Game Development', 'Teaching', 'Mentoring', 'Curriculum Delivery'],
    color: '#fbbf24',
    link: 'https://gcu.edu.pk/',
  },
]
