/** @import { Project } from './types' */

/** @type {Project[]} */
export const projects = [
  { id: 'f1', title: 'Stellar DNA', category: 'Astrophysics', icon: 'fa-solid fa-atom', desc: 'A physics-based simulation exploring the chemical fingerprint of stars through spectral analysis and nucleosynthesis modeling.', tags: ['Python', 'Simulation', 'Physics'], link: 'https://stellar-dna.vercel.app/', featured: true },
  { id: 'f2', title: 'CADS-Bridge', category: 'Business Tech', icon: 'fa-solid fa-building-columns', desc: 'A Bridge between Chartered Accountants and Data Science teams working at a firm in isolation.', tags: ['React', 'Node.js', 'Business Domain'], link: 'https://github.com/HassanNawaz14/CADS-Bridge', featured: true },
  { id: 'f3', title: 'Travel Buddy+', category: 'Travel Tech', icon: 'fa-solid fa-plane-departure', desc: 'A next-generation Travel Planner with AI-powered recommendations, planning tools, and real-time updates.', tags: ['React', 'Node.js', 'AI'], link: 'https://github.com/HassanNawaz14/Travel-Buddy-', featured: true },
  { id: 1, title: 'CPU-Storm', category: 'Operating Systems', icon: 'fas fa-theater-masks', desc: 'A simulation of DoS attack on a CPU scheduler to analyze performance under stress.', tags: ['OS', 'C', 'Simulation'], link: 'https://github.com/HassanNawaz14/CPU-Storm', featured: false },
  { id: 2, title: 'Sentiment Predictor', category: 'Data Science', icon: 'fa-solid fa-brain', desc: 'Complete sentiment analysis pipeline with ML models trained on textual reviews.', tags: ['ML', 'Python', 'Data Science'], link: 'https://github.com/HassanNawaz14/Sentiment-Predictor', featured: false },
  { id: 3, title: 'RecommendationX', category: 'Web Dev', icon: 'fa-solid fa-film', desc: 'Smart movie recommender system with personalized suggestions.', tags: ['JS', 'Node.js', 'CSV'], link: 'https://github.com/HassanNawaz14/RecommendationX', featured: false },
  { id: 4, title: 'GearPro', category: 'Web Dev', icon: 'fa-solid fa-car', desc: 'Car specification database with detailed trim information.', tags: ['APIs', 'Frontend', 'JS'], link: 'https://github.com/HassanNawaz14/GearPro', featured: false },
  { id: 5, title: 'Brick Breaker', category: 'Game Dev', icon: 'fa-solid fa-baseball-ball', desc: '8086 Assembly Language game using video memory and interrupts.', tags: ['Assembly', 'x86', 'Game Dev'], link: 'https://github.com/HassanNawaz14/Brick-Breaker', featured: false },
  { id: 6, title: 'Lib Management Sys', category: 'C++', icon: 'fa-solid fa-book-open', desc: 'High-performance system using complex data structures.', tags: ['C++', 'DSA', 'Efficiency'], link: 'https://github.com/HassanNawaz14/Library-Management-System', featured: false },
  { id: 7, title: 'Space Shooter', category: 'Game Dev', icon: 'fa-solid fa-shuttle-space', desc: 'Classic Space Shooter demo in vanilla Assembly x86.', tags: ['Assembly', 'x86', 'Game Dev'], link: 'https://github.com/HassanNawaz14/Space-Shooter-Assembly-Language', featured: false },
  { id: 8, title: 'LudoWeb', category: 'Game Dev', icon: 'fas fa-dice', desc: 'Web-based Ludo game with 4-player support and responsive design.', tags: ['Logic', 'JS', 'UI/UX'], link: 'https://github.com/HassanNawaz14/LudoWeb', featured: false },
  { id: 9, title: 'Relive App', category: 'C++', icon: 'fa-solid fa-users', desc: 'C++ social network simulation with OOP principles.', tags: ['C++', 'OOP', 'CLI'], link: 'https://github.com/HassanNawaz14/ReLive-CLI-App', featured: false },
  { id: 10, title: 'Solar App', category: 'C++', icon: 'fa-solid fa-solar-panel', desc: 'Solar plan recommendation system based on budget and location.', tags: ['C++', 'Physics', 'CLI'], link: 'https://github.com/HassanNawaz14/Solar-Project', featured: false },
]
